from django.contrib import admin
from app.models import *
admin.site.register(Movie_collections)
admin.site.register(Streaming_collections)
admin.site.register(Event_collections)
admin.site.register(Sports_collections)
admin.site.register(Chennai_Tamil_movies)
admin.site.register(Chennai_Other_movies)
admin.site.register(Chennai_Other1_movies)
admin.site.register(Chennai_Cartoon_movies)
admin.site.register(Streaming1)
admin.site.register(Streaming2)
admin.site.register(Streaming3)
admin.site.register(Streaming4)
admin.site.register(Event1)
admin.site.register(Event2)
admin.site.register(Event3)
admin.site.register(Event4)
admin.site.register(Sport1)
admin.site.register(Sport2)
admin.site.register(Sport3)
admin.site.register(Sport4)
admin.site.register(Movies)
admin.site.register(Stream)
admin.site.register(Sports)
admin.site.register(Events)
admin.site.register(details)
