# Generated by Django 4.2.2 on 2023-07-13 17:24

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=app.models.getFilename)),
                ('Movie_name', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app.models.getFilename)),
                ('Movie_name', models.CharField(max_length=150)),
                ('Quality', models.CharField(max_length=150)),
                ('Languages', models.CharField(max_length=150)),
                ('Concept', models.CharField(max_length=150)),
                ('Cast1', models.CharField(max_length=100)),
                ('Cast2', models.CharField(max_length=100)),
                ('Cast3', models.CharField(max_length=100)),
                ('Cast4', models.CharField(max_length=100)),
                ('Crew1', models.CharField(max_length=100)),
                ('Crew2', models.CharField(max_length=100)),
                ('Crew3', models.CharField(max_length=100)),
                ('Crew4', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movie_collections')),
            ],
        ),
    ]
