# Generated by Django 4.2.2 on 2023-07-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_streaming'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Streaming',
            new_name='Streaming1',
        ),
    ]
