# Generated by Django 4.2.2 on 2023-07-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_sport1_sport2_sport3_sport4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
