# Generated by Django 4.2.2 on 2023-07-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_movies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
