# Generated by Django 4.2.2 on 2023-07-15 15:32

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_sports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sports_collections'),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app.models.getFilename)),
                ('Events_name', models.CharField(max_length=150)),
                ('Date_and_time', models.CharField(max_length=150)),
                ('Place', models.CharField(max_length=150)),
                ('Amount', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event_collections')),
            ],
        ),
    ]
